"""add groups roles postponed_items

Revision ID: 463bcae42a18
Revises: e43c1273e1a3
Create Date: 2026-08-04 00:49:48.647459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463bcae42a18'
down_revision: Union[str, Sequence[str], None] = 'e43c1273e1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('groups_pkey'))
    )
    op.create_index(op.f('ix_groups_created_at'), 'groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_groups_deleted_at'), 'groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_groups_domain'), 'groups', ['domain'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expire_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('auth_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_sessions_pkey'))
    )
    op.create_index(op.f('ix_auth_sessions_created_at'), 'auth_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_deleted_at'), 'auth_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_expire_at'), 'auth_sessions', ['expire_at'], unique=False)
    op.create_table('postponed_items',
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.Column('media_path', sa.String(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('postponed_items_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('postponed_items_pkey'))
    )
    op.create_index(op.f('ix_postponed_items_created_at'), 'postponed_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_postponed_items_deleted_at'), 'postponed_items', ['deleted_at'], unique=False)
    op.create_table('roles',
    sa.Column('role', sa.Enum('admin', 'editor', name='roletype'), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('roles_group_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('roles_user_id_fkey')),
    sa.PrimaryKeyConstraint('role', 'group_id', 'user_id', name=op.f('roles_pkey'))
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'], unique=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_postponed_items_deleted_at'), table_name='postponed_items')
    op.drop_index(op.f('ix_postponed_items_created_at'), table_name='postponed_items')
    op.drop_table('postponed_items')
    op.drop_index(op.f('ix_auth_sessions_expire_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_deleted_at'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_created_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_groups_domain'), table_name='groups')
    op.drop_index(op.f('ix_groups_deleted_at'), table_name='groups')
    op.drop_index(op.f('ix_groups_created_at'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
