"""add scheduled to postponed_items

Revision ID: d2b8a4533eaf
Revises: 5f8a1b2c3d4e
Create Date: 2026-09-10 19:59:34.367783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b8a4533eaf'
down_revision: Union[str, Sequence[str], None] = '5f8a1b2c3d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postponed_items', sa.Column('scheduled', sa.TIMESTAMP(timezone=True), nullable=False))
    op.alter_column('postponed_items', 'text',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('postponed_items', 'media_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=254),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('postponed_items', 'media_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('postponed_items', 'text',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('postponed_items', 'scheduled')
    # ### end Alembic commands ###
